#! /bin/bash
# Capturando una ruta indicar este es un archivo o directorio

echo -n "Digite objeto a comprobar: "
read algo
echo "ud digito $OBJETO"
master  2
master  2
master  2
master  2
master  2
master  2
master  2
master  2
master  2
master  2

FILE=`file $algo`

echo "$FILE"

