#! /bin/bash
# mostrar la ip

echo -n "Digite la interfaz a cosultar su ip: "
read OBJETO 
echo "Digito la interfaz $OBJETO"

sudo ifconfig $OBJETO | grep inet | cut -c10-35 | cut -d'f' -f2 | cut -d: -f2
