#! /bin/bash
# Capturando una ruta indicar este es un archivo o directorio

echo -n "Digite objeto a comprobar: "
read algo
echo "ud digito $OBJETO"
rama 1
rama 1
rama 1
rama 1
rama 1
rama 1
rama 1
rama 1
FILE=`file $algo`

echo "$FILE"

